//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.achievement.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "AchievementTracker", targetNamespace = "http://service.achievement.ibm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AchievementTracker {


    /**
     * 
     * @return
     *     returns java.util.List<com.ibm.achievement.service.AchievementTypesVO>
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAchievementTypes", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindAchievementTypes")
    @ResponseWrapper(localName = "findAchievementTypesResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindAchievementTypesResponse")
    public List<AchievementTypesVO> findAchievementTypes()
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param typeId
     * @return
     *     returns com.ibm.achievement.service.AchievementTypesVO
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAchievementType", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindAchievementType")
    @ResponseWrapper(localName = "findAchievementTypeResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindAchievementTypeResponse")
    public AchievementTypesVO findAchievementType(
        @WebParam(name = "typeId", targetNamespace = "")
        String typeId)
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.ibm.achievement.service.AchievementCatgryVO>
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAchievementCategories", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindAchievementCategories")
    @ResponseWrapper(localName = "findAchievementCategoriesResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindAchievementCategoriesResponse")
    public List<AchievementCatgryVO> findAchievementCategories()
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param achievementVO
     * @return
     *     returns boolean
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveAchievement", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.SaveAchievement")
    @ResponseWrapper(localName = "saveAchievementResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.SaveAchievementResponse")
    public boolean saveAchievement(
        @WebParam(name = "achievementVO", targetNamespace = "")
        AchievementVO achievementVO)
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param employeeId
     * @return
     *     returns java.util.List<com.ibm.achievement.service.AchievementVO>
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAchievementByEmpID", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindAchievementByEmpID")
    @ResponseWrapper(localName = "findAchievementByEmpIDResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindAchievementByEmpIDResponse")
    public List<AchievementVO> findAchievementByEmpID(
        @WebParam(name = "employeeId", targetNamespace = "")
        String employeeId)
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param approverId
     * @return
     *     returns java.util.List<com.ibm.achievement.service.AchievementVO>
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAchievementByApproverID", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindAchievementByApproverID")
    @ResponseWrapper(localName = "findAchievementByApproverIDResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindAchievementByApproverIDResponse")
    public List<AchievementVO> findAchievementByApproverID(
        @WebParam(name = "approverId", targetNamespace = "")
        String approverId)
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param achievementId
     * @return
     *     returns com.ibm.achievement.service.AchievementVO
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAchievementById", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindAchievementById")
    @ResponseWrapper(localName = "findAchievementByIdResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindAchievementByIdResponse")
    public AchievementVO findAchievementById(
        @WebParam(name = "achievementId", targetNamespace = "")
        int achievementId)
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param pointValue
     * @param status
     * @param approverComment
     * @param achievementId
     * @param category
     * @return
     *     returns boolean
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "approveAchievement", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.ApproveAchievement")
    @ResponseWrapper(localName = "approveAchievementResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.ApproveAchievementResponse")
    public boolean approveAchievement(
        @WebParam(name = "achievementId", targetNamespace = "")
        String achievementId,
        @WebParam(name = "status", targetNamespace = "")
        String status,
        @WebParam(name = "category", targetNamespace = "")
        String category,
        @WebParam(name = "pointValue", targetNamespace = "")
        int pointValue,
        @WebParam(name = "approverComment", targetNamespace = "")
        String approverComment)
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param employeeId
     * @return
     *     returns com.ibm.achievement.service.AchievementCountVO
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAchievementSummery", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindAchievementSummery")
    @ResponseWrapper(localName = "findAchievementSummeryResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindAchievementSummeryResponse")
    public AchievementCountVO findAchievementSummery(
        @WebParam(name = "employeeId", targetNamespace = "")
        String employeeId)
        throws AchievementTrackerException_Exception
    ;

}
