//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.achievement.service;

import javax.xml.ws.WebFault;

@WebFault(name = "AchievementTrackerException", targetNamespace = "http://service.achievement.ibm.com/")
public class AchievementTrackerException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AchievementTrackerException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AchievementTrackerException_Exception(String message, AchievementTrackerException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public AchievementTrackerException_Exception(String message, AchievementTrackerException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ibm.achievement.service.AchievementTrackerException
     */
    public AchievementTrackerException getFaultInfo() {
        return faultInfo;
    }

}
