//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.achievement.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for approveAchievement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="approveAchievement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="achievementId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pointValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="approverComment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "approveAchievement", namespace = "http://service.achievement.ibm.com/", propOrder = {
    "achievementId",
    "status",
    "category",
    "pointValue",
    "approverComment"
})
public class ApproveAchievement {

    protected String achievementId;
    protected String status;
    protected String category;
    protected int pointValue;
    protected String approverComment;

    /**
     * Gets the value of the achievementId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAchievementId() {
        return achievementId;
    }

    /**
     * Sets the value of the achievementId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAchievementId(String value) {
        this.achievementId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the pointValue property.
     * 
     */
    public int getPointValue() {
        return pointValue;
    }

    /**
     * Sets the value of the pointValue property.
     * 
     */
    public void setPointValue(int value) {
        this.pointValue = value;
    }

    /**
     * Gets the value of the approverComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApproverComment() {
        return approverComment;
    }

    /**
     * Sets the value of the approverComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApproverComment(String value) {
        this.approverComment = value;
    }

}
