//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.achievement.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "EmployeeManagement", targetNamespace = "http://service.achievement.ibm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeManagement {


    /**
     * 
     * @return
     *     returns java.util.List<com.ibm.achievement.service.EmployeeVO>
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findEmployeesByManagerFlag", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindEmployeesByManagerFlag")
    @ResponseWrapper(localName = "findEmployeesByManagerFlagResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindEmployeesByManagerFlagResponse")
    public List<EmployeeVO> findEmployeesByManagerFlag()
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param emailID
     * @return
     *     returns com.ibm.achievement.service.EmployeeVO
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findEmployeesByEmailID", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindEmployeesByEmailID")
    @ResponseWrapper(localName = "findEmployeesByEmailIDResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindEmployeesByEmailIDResponse")
    public EmployeeVO findEmployeesByEmailID(
        @WebParam(name = "emailID", targetNamespace = "")
        String emailID)
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param empID
     * @return
     *     returns com.ibm.achievement.service.EmployeeVO
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findEmployeesByID", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindEmployeesByID")
    @ResponseWrapper(localName = "findEmployeesByIDResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindEmployeesByIDResponse")
    public EmployeeVO findEmployeesByID(
        @WebParam(name = "empID", targetNamespace = "")
        String empID)
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param lastName
     * @param emailID
     * @param managerFlag
     * @param firstName
     * @return
     *     returns java.util.List<com.ibm.achievement.service.EmployeeVO>
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findEmployees", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindEmployees")
    @ResponseWrapper(localName = "findEmployeesResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindEmployeesResponse")
    public List<EmployeeVO> findEmployees(
        @WebParam(name = "emailID", targetNamespace = "")
        String emailID,
        @WebParam(name = "firstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "lastName", targetNamespace = "")
        String lastName,
        @WebParam(name = "managerFlag", targetNamespace = "")
        String managerFlag)
        throws AchievementTrackerException_Exception
    ;

}
