//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.achievement.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ProjectManagement", targetNamespace = "http://service.achievement.ibm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProjectManagement {


    /**
     * 
     * @return
     *     returns java.util.List<com.ibm.achievement.service.ProjectVO>
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findProjects", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindProjects")
    @ResponseWrapper(localName = "findProjectsResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindProjectsResponse")
    public List<ProjectVO> findProjects()
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param employeeId
     * @return
     *     returns java.util.List<com.ibm.achievement.service.ProjectVO>
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findEmployeeProjects", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindEmployeeProjects")
    @ResponseWrapper(localName = "findEmployeeProjectsResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindEmployeeProjectsResponse")
    public List<ProjectVO> findEmployeeProjects(
        @WebParam(name = "employeeId", targetNamespace = "")
        String employeeId)
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param projectId
     * @return
     *     returns com.ibm.achievement.service.ProjectVO
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findProjectById", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindProjectById")
    @ResponseWrapper(localName = "findProjectByIdResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindProjectByIdResponse")
    public ProjectVO findProjectById(
        @WebParam(name = "projectId", targetNamespace = "")
        String projectId)
        throws AchievementTrackerException_Exception
    ;

}
