//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.achievement.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for saveAchievement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="saveAchievement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="achievementVO" type="{http://service.achievement.ibm.com/}achievementVO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "saveAchievement", namespace = "http://service.achievement.ibm.com/", propOrder = {
    "achievementVO"
})
public class SaveAchievement {

    protected AchievementVO achievementVO;

    /**
     * Gets the value of the achievementVO property.
     * 
     * @return
     *     possible object is
     *     {@link AchievementVO }
     *     
     */
    public AchievementVO getAchievementVO() {
        return achievementVO;
    }

    /**
     * Sets the value of the achievementVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link AchievementVO }
     *     
     */
    public void setAchievementVO(AchievementVO value) {
        this.achievementVO = value;
    }

}
