//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.achievement.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "UserManagement", targetNamespace = "http://service.achievement.ibm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserManagement {


    /**
     * 
     * @param emailId
     * @param password
     * @return
     *     returns com.ibm.achievement.service.EmployeeVO
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isValidUser", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.IsValidUser")
    @ResponseWrapper(localName = "isValidUserResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.IsValidUserResponse")
    public EmployeeVO isValidUser(
        @WebParam(name = "emailId", targetNamespace = "")
        String emailId,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param employeeVO
     * @param password
     * @return
     *     returns boolean
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.RegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.RegisterUserResponse")
    public boolean registerUser(
        @WebParam(name = "employeeVO", targetNamespace = "")
        EmployeeVO employeeVO,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param activeFlag
     * @return
     *     returns java.util.List<com.ibm.achievement.service.EmployeeVO>
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserByActiveFlag", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindUserByActiveFlag")
    @ResponseWrapper(localName = "findUserByActiveFlagResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.FindUserByActiveFlagResponse")
    public List<EmployeeVO> findUserByActiveFlag(
        @WebParam(name = "activeFlag", targetNamespace = "")
        String activeFlag)
        throws AchievementTrackerException_Exception
    ;

    /**
     * 
     * @param activeFlag
     * @param emailId
     * @return
     *     returns boolean
     * @throws AchievementTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUserActiveFlag", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.UpdateUserActiveFlag")
    @ResponseWrapper(localName = "updateUserActiveFlagResponse", targetNamespace = "http://service.achievement.ibm.com/", className = "com.ibm.achievement.service.UpdateUserActiveFlagResponse")
    public boolean updateUserActiveFlag(
        @WebParam(name = "activeFlag", targetNamespace = "")
        String activeFlag,
        @WebParam(name = "emailId", targetNamespace = "")
        String emailId)
        throws AchievementTrackerException_Exception
    ;

}
